// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "Address": {
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "city": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "is_default": {
                        "type": "boolean"
                    },
                    "label": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "phone": {
                        "type": "string"
                    },
                    "postal_code": {
                        "type": "string"
                    },
                    "province": {
                        "type": "string"
                    }
                },
                "required": [
                    "address",
                    "city",
                    "id",
                    "is_default",
                    "label",
                    "name",
                    "phone",
                    "postal_code",
                    "province"
                ],
                "type": "object"
            },
            "AddressRequest": {
                "properties": {
                    "address": {
                        "type": "string"
                    },
                    "city": {
                        "type": "string"
                    },
                    "is_default": {
                        "type": "boolean"
                    },
                    "label": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "phone": {
                        "type": "string"
                    },
                    "postal_code": {
                        "type": "string"
                    },
                    "province": {
                        "type": "string"
                    }
                },
                "required": [
                    "address",
                    "city",
                    "label",
                    "name",
                    "phone",
                    "postal_code",
                    "province"
                ],
                "type": "object"
            },
            "Brand": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "product_count": {
                        "type": "integer"
                    }
                },
                "required": [
                    "id",
                    "name",
                    "product_count"
                ],
                "type": "object"
            },
            "Cart": {
                "properties": {
                    "items": {
                        "items": {
                            "$ref": "#/components/schemas/CartItem"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "subtotal_idr": {
                        "type": "integer"
                    }
                },
                "required": [
                    "items",
                    "subtotal_idr"
                ],
                "type": "object"
            },
            "CartItem": {
                "properties": {
                    "created_at": {
                        "type": "string"
                    },
                    "id_product": {
                        "type": "string"
                    },
                    "id_variant": {
                        "type": "string"
                    },
                    "inventory": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "original_price_idr": {
                        "type": "integer"
                    },
                    "price_idr": {
                        "type": "integer"
                    },
                    "quantity": {
                        "type": "integer"
                    },
                    "sku": {
                        "type": "string"
                    },
                    "urls": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "variant_options": {
                        "items": {
                            "$ref": "#/components/schemas/VariantOption"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "required": [
                    "created_at",
                    "id_product",
                    "id_variant",
                    "inventory",
                    "name",
                    "original_price_idr",
                    "price_idr",
                    "quantity"
                ],
                "type": "object"
            },
            "CartRequest": {
                "properties": {
                    "id_variant": {
                        "type": "string"
                    },
                    "quantity": {
                        "minimum": 1,
                        "type": "integer"
                    }
                },
                "required": [
                    "id_variant",
                    "quantity"
                ],
                "type": "object"
            },
            "Category": {
                "properties": {
                    "icon": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "img": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "product_count": {
                        "type": "integer"
                    }
                },
                "required": [
                    "id",
                    "name",
                    "product_count"
                ],
                "type": "object"
            },
            "LoginRequest": {
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                },
                "required": [
                    "email",
                    "password"
                ],
                "type": "object"
            },
            "Order": {
                "properties": {
                    "created_at": {
                        "type": "string"
                    },
                    "discount_idr": {
                        "type": "integer"
                    },
                    "id": {
                        "type": "string"
                    },
                    "id_payment": {
                        "type": "string"
                    },
                    "items": {
                        "items": {
                            "$ref": "#/components/schemas/OrderItem"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "promo_code": {
                        "type": "string"
                    },
                    "ship_address": {
                        "type": "string"
                    },
                    "ship_cost_idr": {
                        "type": "integer"
                    },
                    "ship_email": {
                        "type": "string"
                    },
                    "ship_method": {
                        "type": "string"
                    },
                    "ship_name": {
                        "type": "string"
                    },
                    "ship_note": {
                        "type": "string"
                    },
                    "ship_phone": {
                        "type": "string"
                    },
                    "status": {
                        "enum": [
                            "pending",
                            "packed",
                            "shipped",
                            "delivered",
                            "cancelled"
                        ],
                        "type": "string"
                    },
                    "subtotal_idr": {
                        "type": "integer"
                    },
                    "total_idr": {
                        "type": "integer"
                    }
                },
                "required": [
                    "created_at",
                    "discount_idr",
                    "id",
                    "id_payment",
                    "items",
                    "ship_address",
                    "ship_cost_idr",
                    "ship_email",
                    "ship_method",
                    "ship_name",
                    "ship_phone",
                    "status",
                    "subtotal_idr",
                    "total_idr"
                ],
                "type": "object"
            },
            "OrderItem": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "id_variant": {
                        "type": "string"
                    },
                    "product_name": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "integer"
                    },
                    "unit_price_idr": {
                        "type": "integer"
                    },
                    "variant_name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "product_name",
                    "quantity",
                    "unit_price_idr"
                ],
                "type": "object"
            },
            "OrderRequest": {
                "properties": {
                    "id_address": {
                        "type": "string"
                    },
                    "id_payment": {
                        "type": "string"
                    },
                    "promo_code": {
                        "type": "string"
                    },
                    "ship_method": {
                        "type": "string"
                    },
                    "ship_note": {
                        "type": "string"
                    }
                },
                "required": [
                    "id_address",
                    "id_payment",
                    "ship_method"
                ],
                "type": "object"
            },
            "PaymentMethod": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "metadata": {
                        "type": "object"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "metadata",
                    "name"
                ],
                "type": "object"
            },
            "Problem": {
                "properties": {
                    "detail": {
                        "type": "string"
                    },
                    "status": {
                        "type": "integer"
                    },
                    "title": {
                        "type": "string"
                    }
                },
                "required": [
                    "status",
                    "title"
                ],
                "type": "object"
            },
            "Product": {
                "properties": {
                    "brand": {
                        "type": "string"
                    },
                    "category": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "original_price_idr": {
                        "type": "integer"
                    },
                    "price_idr": {
                        "type": "integer"
                    },
                    "rating": {
                        "type": "number"
                    },
                    "rating_count": {
                        "type": "integer"
                    },
                    "stock": {
                        "type": "integer"
                    },
                    "updated_at": {
                        "type": "string"
                    },
                    "urls": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "variants": {
                        "items": {
                            "$ref": "#/components/schemas/ProductVariant"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "required": [
                    "created_at",
                    "id",
                    "name",
                    "rating_count",
                    "stock",
                    "updated_at"
                ],
                "type": "object"
            },
            "ProductVariant": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "options": {
                        "items": {
                            "$ref": "#/components/schemas/VariantOption"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "original_price_idr": {
                        "type": "integer"
                    },
                    "price_idr": {
                        "type": "integer"
                    },
                    "sku": {
                        "type": "string"
                    },
                    "stock": {
                        "type": "integer"
                    }
                },
                "required": [
                    "id",
                    "options",
                    "original_price_idr",
                    "price_idr",
                    "stock"
                ],
                "type": "object"
            },
            "RegisterRequest": {
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "password": {
                        "minLength": 8,
                        "type": "string"
                    }
                },
                "required": [
                    "email",
                    "name",
                    "password"
                ],
                "type": "object"
            },
            "ShippingMethod": {
                "properties": {
                    "cost_idr": {
                        "type": "integer"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "cost_idr",
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "TokenResponse": {
                "properties": {
                    "token": {
                        "type": "string"
                    }
                },
                "required": [
                    "token"
                ],
                "type": "object"
            },
            "User": {
                "properties": {
                    "avatar": {
                        "type": "string"
                    },
                    "birthdate": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "gender": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "phone": {
                        "type": "string"
                    },
                    "roles": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "updated_at": {
                        "type": "string"
                    }
                },
                "required": [
                    "created_at",
                    "email",
                    "id",
                    "roles",
                    "updated_at"
                ],
                "type": "object"
            },
            "UserPayment": {
                "properties": {
                    "created_at": {
                        "type": "string"
                    },
                    "data": {
                        "type": "object"
                    },
                    "id": {
                        "type": "string"
                    },
                    "id_payment": {
                        "type": "string"
                    },
                    "is_default": {
                        "type": "boolean"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "created_at",
                    "data",
                    "id",
                    "id_payment",
                    "is_default",
                    "type"
                ],
                "type": "object"
            },
            "VariantOption": {
                "properties": {
                    "option": {
                        "type": "string"
                    },
                    "value": {
                        "type": "string"
                    }
                },
                "required": [
                    "option",
                    "value"
                ],
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "scheme": "bearer",
                "type": "http"
            }
        }
    },
    "info": {
        "contact": {
            "email": "suhartanto@kekkon.nexus",
            "name": "Ryan Suhartanto",
            "url": "https://github.com/ryansuhartanto/koda-b8-backend"
        },
        "description": "{{escape .Description}}",
        "license": {
            "name": "MIT"
        },
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/auth/login": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/LoginRequest",
                                "summary": "body",
                                "description": "Credentials"
                            }
                        }
                    },
                    "description": "Credentials",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/TokenResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid body"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid credentials"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "Exchange credentials for a token",
                "tags": [
                    "auth"
                ]
            }
        },
        "/auth/register": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/RegisterRequest",
                                "summary": "body",
                                "description": "Credentials"
                            }
                        }
                    },
                    "description": "Credentials",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/TokenResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid body"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Email already registered"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "Register an account",
                "tags": [
                    "auth"
                ]
            }
        },
        "/brands": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/Brand"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "List brands and how many products each holds",
                "tags": [
                    "catalog"
                ]
            }
        },
        "/categories": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/Category"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "List categories and how many products each holds",
                "tags": [
                    "catalog"
                ]
            }
        },
        "/healthz": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {
                                        "type": "string"
                                    },
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Database unreachable"
                    }
                },
                "summary": "Liveness and database reachability",
                "tags": [
                    "meta"
                ]
            }
        },
        "/me": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "No such user"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "The caller's own profile",
                "tags": [
                    "me"
                ]
            }
        },
        "/me/addresses": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/Address"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List the caller's addresses, default first",
                "tags": [
                    "addresses"
                ]
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/AddressRequest",
                                "summary": "body",
                                "description": "Address"
                            }
                        }
                    },
                    "description": "Address",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Address"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid body"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Add an address to the caller's account",
                "tags": [
                    "addresses"
                ]
            }
        },
        "/me/cart": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Cart"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "The caller's cart and its subtotal",
                "tags": [
                    "cart"
                ]
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CartRequest",
                                "summary": "body",
                                "description": "Line"
                            }
                        }
                    },
                    "description": "Line",
                    "required": true
                },
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid body"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "No such variant"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Set the quantity of one cart line",
                "tags": [
                    "cart"
                ]
            }
        },
        "/me/cart/{id_variant}": {
            "delete": {
                "parameters": [
                    {
                        "description": "Variant sqid",
                        "in": "path",
                        "name": "id_variant",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "No such cart item"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Remove one variant from the cart",
                "tags": [
                    "cart"
                ]
            }
        },
        "/me/orders": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/Order"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "List the caller's orders, newest first",
                "tags": [
                    "orders"
                ]
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/OrderRequest",
                                "summary": "body",
                                "description": "Checkout"
                            }
                        }
                    },
                    "description": "Checkout",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Order"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid body"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "No such address, payment method or shipping method"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Empty cart or insufficient stock"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Turn the caller's cart into an order",
                "tags": [
                    "orders"
                ]
            }
        },
        "/me/payments": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/UserPayment"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Missing or invalid token"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "The caller's saved payment methods",
                "tags": [
                    "me"
                ]
            }
        },
        "/payment-methods": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/PaymentMethod"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "List the payment methods an order can be placed with",
                "tags": [
                    "catalog"
                ]
            }
        },
        "/products": {
            "get": {
                "parameters": [
                    {
                        "description": "Match against the product name",
                        "in": "query",
                        "name": "search",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Category name",
                        "in": "query",
                        "name": "category",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Brand name",
                        "in": "query",
                        "name": "brand",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "One of newest, price_asc, price_desc, rating",
                        "in": "query",
                        "name": "sort",
                        "schema": {
                            "enum": [
                                "newest",
                                "price_asc",
                                "price_desc",
                                "rating"
                            ],
                            "type": "string"
                        }
                    },
                    {
                        "description": "Rows to return, 1 to 100",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "default": 20,
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Rows to skip",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "default": 0,
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/Product"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK",
                        "headers": {
                            "Link": {
                                "description": "RFC 8288 pagination links: self, first, last, prev, next",
                                "schema": {
                                    "type": "string"
                                }
                            },
                            "X-Total-Count": {
                                "description": "Rows matching the filter, ignoring limit and offset",
                                "schema": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid query"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "List products",
                "tags": [
                    "products"
                ]
            }
        },
        "/products/{id_product}": {
            "get": {
                "parameters": [
                    {
                        "description": "Product sqid",
                        "in": "path",
                        "name": "id_product",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Product"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "No such product"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "Fetch one product and its variants",
                "tags": [
                    "products"
                ]
            }
        },
        "/shipping-methods": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/ShippingMethod"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "List shipping methods and their cost",
                "tags": [
                    "catalog"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "http://localhost:3001"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "BeliMudah API",
	Description:      "E-commerce API for the BeliMudah storefront.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
