import type { Catalog } from "#/client";

export type Scenario = {
	name: string;
	path: string;
	method?: "GET" | "POST" | "PATCH" | "DELETE";
	auth?: boolean;
	token?: string;
	body?: unknown;
	bodyFromFixture?: "credentials" | "order" | "unknownShipMethod";
	status: number;
	schema?: string;
	array?: boolean;
	mutates?: boolean;
	// a JWT embeds iat, so even one service answers differently twice
	nondeterministic?: boolean;
};

export const scenarios = (catalog: Catalog): Scenario[] => [
	{ name: "GET /", path: "/", status: 301 },
	{ name: "GET /healthz", path: "/healthz", status: 200 },

	{
		name: "products, default",
		path: "/products",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, limited",
		path: "/products?limit=3",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, paged",
		path: "/products?limit=2&offset=2",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, last page",
		path: "/products?limit=5&offset=15",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, minimum limit",
		path: "/products?limit=1",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, maximum limit",
		path: "/products?limit=100",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, sort newest",
		path: "/products?sort=newest&limit=3",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, sort price_asc",
		path: "/products?sort=price_asc&limit=3",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, sort price_desc",
		path: "/products?sort=price_desc&limit=3",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, sort rating",
		path: "/products?sort=rating&limit=3",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, by category",
		path: "/products?category=Elektronik",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, by brand",
		path: "/products?brand=SoundWave",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, by search",
		path: "/products?search=yoga",
		status: 200,
		schema: "Product",
		array: true,
	},
	{
		name: "products, offset past the end",
		path: "/products?limit=5&offset=500",
		status: 200,
	},
	{
		name: "products, search with no match",
		path: "/products?search=zzzzzzzz",
		status: 200,
	},
	{
		name: "product, by sqid",
		path: `/products/${catalog.product}`,
		status: 200,
		schema: "Product",
	},
	{
		name: "categories",
		path: "/categories",
		status: 200,
		schema: "Category",
		array: true,
	},
	{
		name: "brands",
		path: "/brands",
		status: 200,
		schema: "Brand",
		array: true,
	},
	{
		name: "payment methods",
		path: "/payment-methods",
		status: 200,
		schema: "PaymentMethod",
		array: true,
	},
	{
		name: "shipping methods",
		path: "/shipping-methods",
		status: 200,
		schema: "ShippingMethod",
		array: true,
	},

	{
		name: "me",
		path: "/me",
		auth: true,
		status: 200,
		schema: "User",
	},
	{
		name: "me without a token",
		path: "/me",
		status: 401,
		schema: "Problem",
	},
	{
		name: "cart",
		path: "/me/cart",
		auth: true,
		status: 200,
		schema: "Cart",
	},
	{
		name: "addresses",
		path: "/me/addresses",
		auth: true,
		status: 200,
		schema: "Address",
		array: true,
	},
	{
		name: "orders",
		path: "/me/orders",
		auth: true,
		status: 200,
		schema: "Order",
		array: true,
	},

	{
		name: "unknown route",
		path: "/no-such-endpoint",
		status: 404,
		schema: "Problem",
	},
	{
		name: "unknown sort",
		path: "/products?sort=bogus",
		status: 400,
		schema: "Problem",
	},
	{
		name: "limit above maximum",
		path: "/products?limit=101",
		status: 400,
		schema: "Problem",
	},
	{
		name: "limit below minimum",
		path: "/products?limit=0",
		status: 400,
		schema: "Problem",
	},
	{
		name: "non-numeric limit",
		path: "/products?limit=abc",
		status: 400,
		schema: "Problem",
	},
	{
		name: "negative offset",
		path: "/products?offset=-1",
		status: 400,
		schema: "Problem",
	},
	{
		name: "non-numeric offset",
		path: "/products?offset=abc",
		status: 400,
		schema: "Problem",
	},
	{
		name: "malformed sqid",
		path: "/products/!!!!!!",
		status: 404,
		schema: "Problem",
	},
	{
		name: "single-character sqid",
		path: "/products/a",
		status: 404,
		schema: "Problem",
	},
	{
		name: "unknown product",
		path: "/products/zzzzzzz",
		status: 404,
		schema: "Problem",
	},

	{
		name: "cart without a token",
		path: "/me/cart",
		status: 401,
		schema: "Problem",
	},
	{
		name: "orders without a token",
		path: "/me/orders",
		status: 401,
		schema: "Problem",
	},
	{
		name: "addresses without a token",
		path: "/me/addresses",
		status: 401,
		schema: "Problem",
	},
	{
		name: "delete cart without a token",
		path: `/me/cart/${catalog.variant}`,
		method: "DELETE",
		status: 401,
		schema: "Problem",
	},
	{
		name: "cart with a malformed token",
		path: "/me/cart",
		token: "not-a-jwt",
		status: 401,
		schema: "Problem",
	},
	{
		name: "orders with a well-formed but unsigned token",
		path: "/me/orders",
		token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjF9.bogus",
		status: 401,
		schema: "Problem",
	},

	{
		name: "all orders without a token",
		path: "/orders",
		status: 401,
		schema: "Problem",
	},
	{
		name: "all orders as a customer",
		path: "/orders",
		auth: true,
		status: 403,
		schema: "Problem",
	},
	{
		name: "create a product without a token",
		path: "/products",
		method: "POST",
		body: { name: "Parity", original_price_idr: 1000 },
		status: 401,
		schema: "Problem",
	},
	{
		name: "create a product as a customer",
		path: "/products",
		method: "POST",
		auth: true,
		body: { name: "Parity", original_price_idr: 1000 },
		status: 403,
		schema: "Problem",
	},
	{
		name: "order status without a token",
		path: `/orders/${catalog.product}`,
		method: "PATCH",
		body: { status: "packed" },
		status: 401,
		schema: "Problem",
	},
	{
		name: "order status as a customer",
		path: `/orders/${catalog.product}`,
		method: "PATCH",
		auth: true,
		body: { status: "packed" },
		status: 403,
		schema: "Problem",
	},
	{
		name: "register with an incomplete body",
		path: "/auth/register",
		method: "POST",
		body: { name: "x" },
		status: 400,
		schema: "Problem",
	},
	{
		name: "register with a short password",
		path: "/auth/register",
		method: "POST",
		body: { name: "x", email: "short@invalid.test", password: "abc" },
		status: 400,
		schema: "Problem",
	},
	{
		name: "register with a malformed email",
		path: "/auth/register",
		method: "POST",
		body: { name: "x", email: "not-an-email", password: "long-enough" },
		status: 400,
		schema: "Problem",
	},
	{
		name: "login with an empty body",
		path: "/auth/login",
		method: "POST",
		body: {},
		status: 400,
		schema: "Problem",
	},
	{
		name: "login with unknown credentials",
		path: "/auth/login",
		method: "POST",
		body: { email: "nobody@invalid.test", password: "wrong-password" },
		status: 401,
		schema: "Problem",
	},
	{
		name: "cart with an empty body",
		path: "/me/cart",
		method: "POST",
		auth: true,
		body: {},
		status: 400,
		schema: "Problem",
	},
	{
		name: "cart with a zero quantity",
		path: "/me/cart",
		method: "POST",
		auth: true,
		body: { id_variant: catalog.variant, quantity: 0 },
		status: 400,
		schema: "Problem",
	},
	{
		name: "cart with an unknown variant",
		path: "/me/cart",
		method: "POST",
		auth: true,
		body: { id_variant: "zzzzzzz", quantity: 1 },
		status: 404,
		schema: "Problem",
	},
	{
		name: "cart delete of an unknown variant",
		path: "/me/cart/zzzzzzz",
		method: "DELETE",
		auth: true,
		status: 404,
		schema: "Problem",
	},
	{
		name: "order with an empty body",
		path: "/me/orders",
		method: "POST",
		auth: true,
		body: {},
		status: 400,
		schema: "Problem",
	},
	{
		name: "order with an unknown address",
		path: "/me/orders",
		method: "POST",
		auth: true,
		body: {
			id_address: "zzzzzzz",
			id_payment: catalog.payment,
			ship_method: "JNE Reguler",
		},
		status: 404,
		schema: "Problem",
	},
	{
		name: "order with an unknown shipping method",
		path: "/me/orders",
		method: "POST",
		auth: true,
		bodyFromFixture: "unknownShipMethod",
		status: 404,
		schema: "Problem",
	},
	{
		name: "address with an incomplete body",
		path: "/me/addresses",
		method: "POST",
		auth: true,
		body: { label: "Rumah" },
		status: 400,
		schema: "Problem",
	},

	{
		name: "login",
		path: "/auth/login",
		method: "POST",
		bodyFromFixture: "credentials",
		status: 200,
		schema: "TokenResponse",
		nondeterministic: true,
	},
	{
		name: "add to the cart",
		path: "/me/cart",
		method: "POST",
		auth: true,
		body: { id_variant: catalog.variant, quantity: 1 },
		status: 204,
		mutates: true,
	},
	{
		name: "drop from the cart",
		path: `/me/cart/${catalog.variant}`,
		method: "DELETE",
		auth: true,
		status: 204,
		mutates: true,
	},
	{
		name: "create an address",
		path: "/me/addresses",
		method: "POST",
		auth: true,
		body: {
			label: "Kantor",
			name: "Fixture",
			phone: "0800000000",
			address: "Jl Fixture 1",
			city: "Jakarta",
			province: "DKI Jakarta",
			postal_code: "10110",
			is_default: false,
		},
		status: 201,
		schema: "Address",
		mutates: true,
	},
	{
		name: "check out",
		path: "/me/orders",
		method: "POST",
		auth: true,
		bodyFromFixture: "order",
		status: 201,
		schema: "Order",
		mutates: true,
	},
];
